application: iovisual3
version: stagef54b
runtime: python27
threadsafe: no
api_version: 1

libraries:
- name: django
  version: "1.2"

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /media
  static_dir: media
  #expiration: 1024d

- url: /(.*\.html)
  static_files: html/\1
  upload: html/(.*\.html)

#Maintenance page
#- url: /.*
#  static_files: maintenance.html
#  upload: maintenance.html

- url: /.*
  script: main_gae.py
